### PR TITLE
Fix renamed CommandLineOption

### PR DESCRIPTION
**Pull request by larsla**
This PR fixes the plugins after CommandLineOption was renamed to PluggableCommandLineOption in the scancode package.

### CODE REVIEW

**Comment by pombredanne** [comment]
@larsla Thank you and sorry for the late review!
Do you mind to add a DCO signoff to your commits or at least as a comment in this PR before I can merge?

**Comment by pombredanne** [comment]
@larsla gentle ping: do you mind to add a DCO signoff, at least as a message in this PR?
This looks like here at the bottom: https://aboutcode.readthedocs.io/en/latest/contributing/writing_good_commit_messages.html
Mine would be: `Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>`
Thanks!

**Comment by pombredanne** [comment]
gentle ping

**Comment by larsla** [comment]
@pombredanne Sorry, these notifications got lost in everything else.
How does it look now?

**Review by pombredanne — APPROVED** [review]
LGTM++
Thanks!

**Pull request merged**
