### PR TITLE
Allow user to override path assumption for system-provided modules

### PR DESCRIPTION
**Pull request by priv-kweihmann**
by optionally using environment variables

### CODE REVIEW

**Review by pombredanne — COMMENTED** [review]
Thank you ++ this makes sense.
Do you think it might be best to have a set of dedicated environment variables such as EXTRACTCODE_7Z_PATH, EXTRACTCODE_LIBARCHIVE_PATH and TYPECODE_LIBMAGIC_PATH and TYPECODE_LIBMAGIC_DB_PATH instead?
May be it is more explicit than overloading LD_LIBRARY_PATH?

**Comment by priv-kweihmann** [comment]
@pombredanne I'm actually a little torn about this - on the one hand the usage of commonly known variable is what I would like to see, on the other I'm not sure about any possible sideeffects, as esp. `LD_LIBRARY_PATH` is pretty invasive.

So I guess it's better to follow your proposal, even if it mean having a larger env set to mind when building - will push a v2 somewhat soon

**Comment by priv-kweihmann** [comment]
BTW does that somehow need to be documented here? If yes, please point me to the right doc to edit

**Comment by pombredanne** [comment]
@priv-kweihmann  you wrote:

> BTW does that somehow need to be documented here? If yes, please point me to the right doc to edit

We can start with a simple doc statement in the README of each plugin.

And beyond this we may want to put this in:

- the main scancode-toolkit documentation
@AyanSinhaMahapatra which place would be best in https://github.com/nexB/scancode-toolkit/tree/develop/docs/source ?

- https://github.com/nexB/typecode README (it does not have a proper doc yet otherwise)
- https://github.com/nexB/extractcode README (it does not have a proper doc yet otherwise)

**Comment by priv-kweihmann** [comment]
New version push, include some brief documentation in the respective plugin dirs - let me know if there is more to do from my side

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne I think there should be a list at https://github.com/nexB/scancode-toolkit/tree/develop/docs/source/plugins with all available ones, would make sense. If that was what you're asking, should that get a separate issue?

**Comment by pombredanne** [comment]
@priv-kweihmann Thank you ++ let me merge all this as well as this other PR https://github.com/nexB/extractcode/pull/18 by @tardyp  which is closely related.
I will refactor the code to get this cascaded behaviour as a general ly available and document way to get pre-built binaries across all the tools and libraries:

1. if there is an environment variable that points to a path use this
2. otherwise try to get a plugin-provided path (which could be a bundled binary or a path provider)
3. otherwise try to get a path from well-known locations (these may be OS-specific) 
4. otherwise try to get a path from the PATH (e.g. which)
5. otherwise fail with a descriptive error message exposing remediation options

**Review by pombredanne — APPROVED** [review]
Thank you ++ 
I am also porting your changes upstream in https://github.com/nexB/extractcode and https://github.com/nexB/typecode directly, so that it can work even if so plugin is installed.

**Pull request merged**
